// Code generated by counterfeiter. DO NOT EDIT.
package kafkafakes

import (
	"context"
	"sync"

	"github.com/dora-network/dora-service-utils/kafka"
	"github.com/twmb/franz-go/pkg/kgo"
)

type FakeClient struct {
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	PingStub        func(context.Context) error
	pingMutex       sync.RWMutex
	pingArgsForCall []struct {
		arg1 context.Context
	}
	pingReturns struct {
		result1 error
	}
	pingReturnsOnCall map[int]struct {
		result1 error
	}
	PollRecordsStub        func(context.Context, int) kgo.Fetches
	pollRecordsMutex       sync.RWMutex
	pollRecordsArgsForCall []struct {
		arg1 context.Context
		arg2 int
	}
	pollRecordsReturns struct {
		result1 kgo.Fetches
	}
	pollRecordsReturnsOnCall map[int]struct {
		result1 kgo.Fetches
	}
	ProduceSyncStub        func(context.Context, ...*kgo.Record) kgo.ProduceResults
	produceSyncMutex       sync.RWMutex
	produceSyncArgsForCall []struct {
		arg1 context.Context
		arg2 []*kgo.Record
	}
	produceSyncReturns struct {
		result1 kgo.ProduceResults
	}
	produceSyncReturnsOnCall map[int]struct {
		result1 kgo.ProduceResults
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeClient) CloseCalls(stub func()) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeClient) Ping(arg1 context.Context) error {
	fake.pingMutex.Lock()
	ret, specificReturn := fake.pingReturnsOnCall[len(fake.pingArgsForCall)]
	fake.pingArgsForCall = append(fake.pingArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.PingStub
	fakeReturns := fake.pingReturns
	fake.recordInvocation("Ping", []interface{}{arg1})
	fake.pingMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) PingCallCount() int {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	return len(fake.pingArgsForCall)
}

func (fake *FakeClient) PingCalls(stub func(context.Context) error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = stub
}

func (fake *FakeClient) PingArgsForCall(i int) context.Context {
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	argsForCall := fake.pingArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) PingReturns(result1 error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	fake.pingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) PingReturnsOnCall(i int, result1 error) {
	fake.pingMutex.Lock()
	defer fake.pingMutex.Unlock()
	fake.PingStub = nil
	if fake.pingReturnsOnCall == nil {
		fake.pingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeClient) PollRecords(arg1 context.Context, arg2 int) kgo.Fetches {
	fake.pollRecordsMutex.Lock()
	ret, specificReturn := fake.pollRecordsReturnsOnCall[len(fake.pollRecordsArgsForCall)]
	fake.pollRecordsArgsForCall = append(fake.pollRecordsArgsForCall, struct {
		arg1 context.Context
		arg2 int
	}{arg1, arg2})
	stub := fake.PollRecordsStub
	fakeReturns := fake.pollRecordsReturns
	fake.recordInvocation("PollRecords", []interface{}{arg1, arg2})
	fake.pollRecordsMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) PollRecordsCallCount() int {
	fake.pollRecordsMutex.RLock()
	defer fake.pollRecordsMutex.RUnlock()
	return len(fake.pollRecordsArgsForCall)
}

func (fake *FakeClient) PollRecordsCalls(stub func(context.Context, int) kgo.Fetches) {
	fake.pollRecordsMutex.Lock()
	defer fake.pollRecordsMutex.Unlock()
	fake.PollRecordsStub = stub
}

func (fake *FakeClient) PollRecordsArgsForCall(i int) (context.Context, int) {
	fake.pollRecordsMutex.RLock()
	defer fake.pollRecordsMutex.RUnlock()
	argsForCall := fake.pollRecordsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) PollRecordsReturns(result1 kgo.Fetches) {
	fake.pollRecordsMutex.Lock()
	defer fake.pollRecordsMutex.Unlock()
	fake.PollRecordsStub = nil
	fake.pollRecordsReturns = struct {
		result1 kgo.Fetches
	}{result1}
}

func (fake *FakeClient) PollRecordsReturnsOnCall(i int, result1 kgo.Fetches) {
	fake.pollRecordsMutex.Lock()
	defer fake.pollRecordsMutex.Unlock()
	fake.PollRecordsStub = nil
	if fake.pollRecordsReturnsOnCall == nil {
		fake.pollRecordsReturnsOnCall = make(map[int]struct {
			result1 kgo.Fetches
		})
	}
	fake.pollRecordsReturnsOnCall[i] = struct {
		result1 kgo.Fetches
	}{result1}
}

func (fake *FakeClient) ProduceSync(arg1 context.Context, arg2 ...*kgo.Record) kgo.ProduceResults {
	fake.produceSyncMutex.Lock()
	ret, specificReturn := fake.produceSyncReturnsOnCall[len(fake.produceSyncArgsForCall)]
	fake.produceSyncArgsForCall = append(fake.produceSyncArgsForCall, struct {
		arg1 context.Context
		arg2 []*kgo.Record
	}{arg1, arg2})
	stub := fake.ProduceSyncStub
	fakeReturns := fake.produceSyncReturns
	fake.recordInvocation("ProduceSync", []interface{}{arg1, arg2})
	fake.produceSyncMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeClient) ProduceSyncCallCount() int {
	fake.produceSyncMutex.RLock()
	defer fake.produceSyncMutex.RUnlock()
	return len(fake.produceSyncArgsForCall)
}

func (fake *FakeClient) ProduceSyncCalls(stub func(context.Context, ...*kgo.Record) kgo.ProduceResults) {
	fake.produceSyncMutex.Lock()
	defer fake.produceSyncMutex.Unlock()
	fake.ProduceSyncStub = stub
}

func (fake *FakeClient) ProduceSyncArgsForCall(i int) (context.Context, []*kgo.Record) {
	fake.produceSyncMutex.RLock()
	defer fake.produceSyncMutex.RUnlock()
	argsForCall := fake.produceSyncArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeClient) ProduceSyncReturns(result1 kgo.ProduceResults) {
	fake.produceSyncMutex.Lock()
	defer fake.produceSyncMutex.Unlock()
	fake.ProduceSyncStub = nil
	fake.produceSyncReturns = struct {
		result1 kgo.ProduceResults
	}{result1}
}

func (fake *FakeClient) ProduceSyncReturnsOnCall(i int, result1 kgo.ProduceResults) {
	fake.produceSyncMutex.Lock()
	defer fake.produceSyncMutex.Unlock()
	fake.ProduceSyncStub = nil
	if fake.produceSyncReturnsOnCall == nil {
		fake.produceSyncReturnsOnCall = make(map[int]struct {
			result1 kgo.ProduceResults
		})
	}
	fake.produceSyncReturnsOnCall[i] = struct {
		result1 kgo.ProduceResults
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.pingMutex.RLock()
	defer fake.pingMutex.RUnlock()
	fake.pollRecordsMutex.RLock()
	defer fake.pollRecordsMutex.RUnlock()
	fake.produceSyncMutex.RLock()
	defer fake.produceSyncMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ kafka.Client = new(FakeClient)
