package kafka

const (
	DefaultOrderTopic                   = "dora.network.orders.incoming"
	DefaultOrderStatusTopic             = "dora.network.orders.status.updates"
	DefaultMatchedOrderTopic            = "dora.network.orders.matched"
	DefaultOrderBookAdminTopic          = "dora.network.orderbook.admin"
	DefaultOrderBookStatusTopic         = "dora.network.orderbook.status"
	DefaultOrderBookUpdatesTopic        = "dora.network.orderbook.updates"
	DefaultOrderBookSnapshotTopic       = "dora.network.orderbook.snapshots"
	DefaultOrderBookRequestsTopic       = "dora.network.orderbook.requests"
	DefaultAssetRequestsTopic           = "dora.network.assets.requests"
	DefaultAssetSnapshotTopic           = "dora.network.assets.snapshots"
	DefaultAssetUpdatesTopic            = "dora.network.assets.updates"
	DefaultUserLedgerRequestsTopic      = "dora.network.user.ledger.requests"
	DefaultUserLedgerSnapshotsTopic     = "dora.network.user.ledger.snapshots"
	DefaultUserLedgerUpdatesTopic       = "dora.network.user.ledger.updates"
	DefaultLeverageRequestsTopic        = "dora.network.leverage.requests"
	DefaultLeverageSnapshotsTopic       = "dora.network.leverage.snapshots"
	DefaultLeverageUpdatesTopic         = "dora.network.leverage.updates"
	DefaultPoolLiquidityRequestsTopic   = "dora.network.pool.liquidity.requests"
	DefaultPoolLiquiditySnapshotsTopic  = "dora.network.pool.liquidity.snapshots"
	DefaultPoolLiquidityUpdatesTopic    = "dora.network.pool.liquidity.updates"
	DefaultTransactionsTopic            = "dora.network.transactions"
	DefaultAddTransactionsRequestTopic  = "dora.network.add.transactions.request"
	DefaultAddTransactionsResponseTopic = "dora.network.add.transactions.response"
	DefaultTradesRequestTopic           = "dora.network.trades.request"
	DefaultTradesResponseTopic          = "dora.network.trades.response"
	DefaultTradesUpdateTopic            = "dora.network.trades.updates"
)
